### ISSUE TITLE
GetRootDse on LDAPConnection returns an exception 

### ISSUE THREAD

**Issue by G31st** [flamencist/ldap4net#113] opened 2021-02-26 11:32 UTC
While running the unit test against and enterprise domain an exception is raised when using the GetRootDse method.

**To Reproduce**
Run the Unit Test from your the code base called : [Fact] public async Task LdapConnection_GetRootDse_Returns_Server_Information()

![image](https://user-images.githubusercontent.com/52254120/109296509-12465400-7839-11eb-9788-2f5ebe55c6cf.png)

An exception should be produced : 
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Collections.ObjectModel.KeyedCollection`2.AddKey(TKey key, TItem item)
   at System.Collections.ObjectModel.KeyedCollection`2.InsertItem(Int32 index, TItem item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at LdapForNet.LdapSearchExtensions.GetRootDse(ILdapConnection connection) in C:\Development\public\ldap4net\LdapForNet\LdapSearchExtensions.cs:line 39
   at LdapForNetTests.LdapSearchExtensionsTests.<LdapConnection_GetRootDse_Returns_Server_Information>d__2.MoveNext() in C:\Development\public\ldap4net\LdapForNet.Tests\LdapSearchExtensionsTests.cs:line 53

**Expected behavior**
Method should return server info. 

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Library version 2.7.11
 - .NET\core\netcoreapp3.1
 - LDAP server Active Directory

**Comment by Reelix** [comment] 2021-05-21 02:25
Potentially similar issue - Similar code - Similar duplicate error

LdapForNet Version 2.7.11

```
using (LdapConnection ldapConnection = new LdapConnection())
{
    LdapCredential anonLDAPCreds = new LdapCredential();
    ldapConnection.Connect(ip, ldapPort);
    ldapConnection.Bind(Native.LdapAuthType.Simple, ldapCreds);
    try
    {
        ldapConnection.GetRootDse();
    }
    catch (Exception ex)
    {
        Console.WriteLine("Error: " + ex.Message);

        var searchEntries = ldapConnection.Search(null, "(objectclass=*)", scope: Native.LdapSearchScope.LDAP_SCOPE_BASE);
        string test = searchEntries[0].DirectoryAttributes["defaultNamingContext"].GetValue<string>();
        Console.WriteLine(test);
    }
    Console.ReadLine();
  }
```

Output:
```
Error: An item with the same key has already been added. Key: supportedSASLMechanisms
DC=ustoun,DC=local
```

**Comment by flamencist** [comment] 2022-03-26 18:03
duplicate of #162

**Closed by flamencist** 2022-03-26 18:03 UTC
